/**
 * Public storefront catalog: categories and products as the customer-facing
 * pages (home, shop, search, product detail) consume them. This mirrors the
 * shape the NestJS catalog controller actually returns — the same product
 * record the admin Inventory pages manage (see inventory.ts), plus the
 * storefront-only promo fields (originalPrice/promoPrice/promotion).
 */

import type { ProductStatus, ProductVariant, VariantOption } from "./inventory";

/** A tile in "Shop by Categories" / the shop page category filter. */
export type StorefrontCategory = {
  id: string;
  /** URL-safe identifier used in ?category=<slug> */
  slug: string;
  name: string;
  image?: string | null;
  /** Position in the storefront category list */
  displayOrder: number;
  productCount: number;
};

export type ProductPromotion = {
  id: string;
  name: string;
  /** e.g. "DISCOUNT_DEAL" */
  type: string;
  discountType: "PERCENTAGE" | "FIXED";
  discountValue: number;
  code?: string | null;
};

/**
 * A product as shown on the storefront: home sections, shop grid/list,
 * search results, related products and the product detail page.
 */
/** The store that sells a product (multi-tenant: every product belongs to one). */
export type ProductStore = {
  id: string;
  name: string;
  slug?: string;
  logo?: string | null;
};

export type StorefrontProduct = {
  id: string;
  /** The store selling this product; the cart groups items by it */
  store: ProductStore;
  /** Auto-generated by the backend, e.g. "PRD-0010" */
  code: string;
  name: string;
  slug: string;
  description?: string | null;
  shortDescription?: string | null;
  /** Primary + gallery images, first is the cover image */
  images: string[];
  categoryId: string;
  category: { id: string; name: string; slug: string };
  sku: string;
  variantOption: VariantOption;
  variants: ProductVariant[];
  /** Unit of measurement, e.g. "pc", "kg", "pack", "tray" */
  unitType: string;
  unitPrice: number;
  /** Struck-through price when on promotion; equal to unitPrice otherwise */
  originalPrice?: number;
  /** The price to actually charge when a promotion is active */
  promoPrice?: number | null;
  /** e.g. 15 -> "15% OFF" badge, derived from the active promotion */
  discountPercent?: number | null;
  promotion?: ProductPromotion | null;
  weight?: number | null;
  stock: number;
  /** Stock level that should trigger a "Low Stock" note */
  reorderLevel: number;
  status: ProductStatus;
  isFeatured: boolean;
  tags: string[];
  displayOrder: number;
  unitsSold: number;
  createdAt: string;
  updatedAt: string;
};

/** Query params for the shop and search pages: filters, sort and pagination. */
export type ListStorefrontProductsParams = {
  /** Matches product name/SKU */
  search?: string;
  /** Category slug(s); omit or "all" for every category */
  category?: string | string[];
  /** Only products carrying this tag, for home-page sections */
  tag?: string;
  minPrice?: number;
  maxPrice?: number;
  /** Product type filter on the search page, e.g. "fresh" | "frozen" | "processed" */
  types?: string[];
  /** "in-stock" | "delivery" | "pickup" */
  availability?: string[];
  /** lowercase variant names, e.g. "small" */
  sizes?: string[];
  /** "nearest" puts products from the closest stores first (needs the visitor's location) */
  sort?: "newest" | "price_asc" | "price_desc" | "name_asc" | "best-selling" | "trending" | "nearest"
   
  /** Only products from stores with a location within this many km of the visitor (needs their location) */
  radiusKm?: number;
  /** Only products with an active promotion */
  onSale?: boolean;
  /** Only this store's products (store slug) */
  store?: string;
  page?: number;
  perPage?: number;
};

export type ListRelatedProductsParams = {
  slug: string;
  limit?: number;
};